---

- name: dunst | install
  become: true
  community.general.pacman:
    name: dunst
    state: present

- name: dunst | link config
  ansible.builtin.file:
    state: link
    src: "{{ window_mgr.dunst.config_src }}"
    dest: "{{ window_mgr.dunst.config_dst }}"
