---
- name: herbstluftwm | install
  when: "ansible_os_family == 'Archlinux'"
  become: true
  community.general.pacman:
    name: herbstluftwm
    state: present

- name: herbstluftwm | link config
  ansible.builtin.file:
    state: link
    src: "{{ window_mgr.config_src }}"
    dest: "{{ window_mgr.config_dst }}"
