---

- name: picom | install (Arch)
  when: "ansible_distribution == 'Archlinux'"
  community.general.pacman:
    name: picom
    state: present

- name: picom | link config
  when: "window_mgr.picom.enabled"
  ansible.builtin.file:
    state: link
    src: "{{ window_mgr.picom.config_src }}"
    dest: "{{ window_mgr.picom.config_dst }}"
