---

- name: polybar | install
  when: "ansible_distribution == 'Archlinux'"
  kewlfft.aur.aur:
    name: polybar
    state: present

- name: polybar | link config
  when: "window_mgr.polybar.enabled"
  ansible.builtin.file:
    state: link
    src: "{{ window_mgr.polybar.config_src }}"
    dest: "{{ window_mgr.polybar.config_dst }}"
