---

- name: rofi | install
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - rofi
    - rofi-calc

- name: rofi | link config
  ansible.builtin.file:
    state: link
    src: "{{ window_mgr.rofi.config_src }}"
    dest: "{{ window_mgr.rofi.config_dst }}"
