---

- name: polybar | install
  when: "ansible_distribution == 'Archlinux'"
  pacman:
    name: polybar
    state: present
    executable: yay

- name: polybar | link config
  when: "window_mgr.polybar.enabled"
  file:
    state: link
    src: "{{ window_mgr.polybar.config_src }}"
    dest: "{{ window_mgr.polybar.config_dst }}"
