---

- name: install ({{ ansible_os_family | lower}})
  include: "{{ ansible_os_family }}.yml"

- name: find binary path
  ansible.builtin.command: which fish
  register: fish_path

- name: ensure present in /etc/shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    state: present
    line: "{{ fish_path.stdout }}"

- name: set as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: link config
  ansible.builtin.file:
    src: "{{ fish.config_src }}"
    dest: "{{ fish.config_dest }}"
    state: link

- name: run setup
  ansible.builtin.shell:
    cmd: source {{ fish.config_dest }}/setup.fish
    executable: "{{ fish_path.stdout }}"

### Fisher ###
- name: fisher | fetch install script
  when: "fish.fisher_install"
  ansible.builtin.get_url:
    url: "{{ fish.fisher_url }}"
    dest: "{{ fish.fisher_dest }}"

- name: fisher | install plugins
  when: "fish.fisher_install_plugins == True"
  ansible.builtin.shell:
    cmd: source {{ fish.fisher_dest }} && fisher update
    executable: "{{ fish_path.stdout }}"
