---

- name: fish | install (macos)
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew:
    name: fish
    state: present

- name: fish | install (archlinux)
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name: fish
    state: present

- name: fish | find binary path
  ansible.builtin.command: which fish
  register: fish_path

- name: fish | ensure present in /etc/shells
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    state: present
    line: "{{ fish_path.stdout }}"

- name: fish | set as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: fish | link config
  ansible.builtin.file:
    src: "{{ fish.config_src }}"
    dest: "{{ fish.config_dest }}"
    state: link

- name: fish | run setup
  ansible.builtin.shell:
    cmd: source {{ fish.config_dest }}/setup.fish
    executable: "{{ fish_path.stdout }}"

### Fisher ###
- name: fisher | fetch install script
  when: "fish.fisher_install"
  ansible.builtin.get_url:
    url: "{{ fish.fisher_url }}"
    dest: "{{ fish.fisher_dest }}"

- name: fisher | install plugins
  when: "fish.fisher_install_plugins == True"
  ansible.builtin.shell:
    cmd: source {{ fish.fisher_dest }} && fisher update
    executable: "{{ fish_path.stdout }}"
