---

- name: shell_tools | install (brew)
  when: |
    ansible_os_family == 'Darwin'
    and 'cask' not in item
    and ansible_os_family|lower not in item.skip|default([])
  with_items: "{{ shell_tools }}"
  community.general.homebrew:
    # msg: "install {{ 'cask' if 'cask' in item else 'non-cask'}} {{ item.brew | default(item.name) }}"
    name: "{{ item.package | default(item.name) }}"
    state: present

- name: shell_tools | install (brew cask)
  when: |
    ansible_os_family == 'Darwin'
    and 'cask' in item
    and ansible_os_family|lower not in item.skip|default([])
  with_items: "{{ shell_tools }}"
  community.general.homebrew_cask:
    # msg: "install {{ 'cask' if 'cask' in item else 'non-cask'}} {{ item.brew | default(item.name) }}"
    name: "{{ item.package | default(item.name) }}"
    state: present

- name: shell_tools | install (pacman)
  when: |
    ansible_os_family == 'Archlinux'
    and 'aur' not in item
    and ansible_os_family|lower not in item.skip|default([])
  with_items: "{{ shell_tools }}"
  become: true
  community.general.pacman:
    name: "{{ item.package | default(item.name) }}"
    state: present

- name: shell_tools | install (aur)
  when: |
    ansible_os_family == 'Archlinux'
    and 'aur' in item
    and ansible_os_family|lower not in item.skip|default([])
  with_items: "{{ shell_tools }}"
  kewlfft.aur.aur:
    name: "{{ item.package | default(item.name) }}"
    state: present
    become: yes
    become_user: aur_builder
