---
- name: Install X server
  become: true
  pacman:
    name: "{{ xorg_pacman_packages }}"
    state: present

- name: Link xinitrc
  file:
    state: link
    src: "{{ xorg_config_src }}"
    dest: "{{ xorg_config_dst }}"