---

- name: macos | change preferences
  ansible.builtin.script: "macos.sh"

- include_tasks: homebrew.yml
  tags: homebrew

- include_tasks: alfred.yml
  tags: alfred

- include_tasks: karabiner.yml
  tags: karabiner
  when: "ansible_os_family == 'Darwin'"
