---

- name: bluetooth | install packages
  become: true
  community.general.pacman:
    name:
    - bluez
    - bluez-utils
    - blueman
    state: present

- name: bluetooth | enable service
  become: true
  ansible.builtin.service:
    name: bluetooth
    enabled: yes
    state: started
