---

- name: base
  include: base.yml
  tags: arch-base

- name: yay
  include: yay.yml

- name: user
  include: user.yml
  tags: arch-user

- name: audio
  include: audio.yml

- name: bluetooth
  include: bluetooth.yml

- name: display
  include: display.yml

- name: x11
  include: x11.yml

- name: fonts
  include: fonts.yml
  tags: fonts

- name: misc
  include: misc.yml
  tags: arch-misc
