---

- name: base
  include: base.yml
  tags: arch-base

- name: yay
  include: yay.yml
  tags: arch-yay

- name: user
  include: user.yml
  tags: arch-user

- name: audio
  include: audio.yml
  tags: arch-audio

- name: bluetooth
  include: bluetooth.yml
  tags: arch-bluetooth

- name: display
  include: display.yml
  tags: arch-display

- name: x11
  include: x11.yml
  tags: arch-x11

- name: fonts
  include: fonts.yml
  tags: fonts

- name: network
  include: network.yml
  tags: arch-network

- name: misc
  include: misc.yml
  tags: arch-misc
