---

- name: network | NetworkManager
  become: true
  community.general.pacman:
    name:
      - networkmanager
      - polkit
    state: present

- name: wireguard | install
  become: true
  community.general.pacman:
    name: wireguard-tools
    state: present
