---

- name: x11 | install packages
  become: true
  community.general.pacman:
    name:
    - xorg
    - xorg-xinit
    - xorg-xmodmap
    state: present

- name: x11 | link config
  ansible.builtin.file:
    state: link
    src: "{{ xorg.config_src }}"
    dest: "{{ xorg.config_dest }}"
