---

- name: x11 | install packages
  community.general.pacman:
    name:
    - xorg
    - xorg-init
    - xorg-xmodmap
    state: present

- name: x11 | link config
  ansible.builtin.file:
    state: link
    src: "{{ xorg_config_src }}"
    dest: "{{ xorg_config_dst }}"
