---

- name: arch | check installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: yay | clone repository
  when: "'yay' not in ansible_facts.packages"
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/tmp/yay"
    version: HEAD

- name: yay | install deps
  when: "'yay' not in ansible_facts.packages"
  become: true
  community.general.pacman:
    name: base-devel
    state: present

- name: yay | install
  when: "'yay' not in ansible_facts.packages"
  ansible.builtin.command:
    cmd: "makepkg -si --noconfirm"
    chdir: "/tmp/yay"

- name: aur | create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: aur | nopasswd sudo for the `aur_builder`
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
