---

- name: install | macos (x86)
  community.general.homebrew_cask:
    name: alacritty
    state: present
  when: "ansible_distribution == 'Linux' and ansible_architecture == 'x86_64'"

- name: install | archlinux
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name: alacritty
    state: present

- name: link config
  ansible.builtin.file:
    src: "{{ alacritty.config_src }}"
    dest: "{{ alacritty.config_dest }}"
    state: link
