---

- name: bitwarden | install | macos
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew_cask:
    name: bitwarden
    state: present

- name: bitwarden | install | archlinux
  become: true
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name: bitwarden
    state: present
