---
- name: discord | install | macos
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew_cask:
    name: discord
    state: present

- name: discord | install | archlinux
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name: discord
    state: present
