---

- name: spotify | install (macos)
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew_cask:
    name: spotify
    state: present

- name: spotify | install (archlinux)
  when: "ansible_os_family == 'Archlinux'"
  kewlfft.aur.aur:
    name: spotify
    state: present

# Provide the qdbus command to get info from Spotify via DBus
- name: spotify | install qt5-tools (archlinux)
  become: true
  community.general.pacman:
    name: qt5-tools
    state: present
