---

- name: whatsapp | install (macos)
  become: true
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew_cask:
    name: whatsapp
    state: present

- name: whatsapp | install (arch)
  when: "ansible_os_family == 'Archlinux'"
  kewlfft.aur.aur:
    name: whatsapp-nativefier
    state: present
