---
- name: Ensure tmux is installed (Mac)
  homebrew:
    name: tmux
    state: present
  when: "ansible_distribution == 'MacOSX'"

- name: Ensure tmux is installed (Arch)
  when: "ansible_os_family == 'Archlinux'"
  pacman:
    name: tmux
    state: present

- name: Link tmux config
  file:
    src: "{{ tmux_config_src }}"
    dest: "{{ tmux_config_dst }}"
    state: link
  when: "tmux_config_link == True"
