---

- name: fonts | create directory
  when: "ansible_distribution in ['Archlinux','Ubuntu','RedHat','Fedora']"
  become: true
  become_user: "{{ ansible_user_id }}"
  file:
    dest: "~/.local/share/fonts"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_id }}"

- name: fonts | install (macos)
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew_cask:
    name:
    - font-hack-nerd-font
    - font-fira-code-nerd-font
    - font-jetbrains-mono-nerd-font
    state: present

- name: fonts | install (archlinux)
  become: true
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name:
    - ttf-liberation
    - noto-fonts
    - noto-fonts-extra
    - noto-fonts-cjk
    - noto-fonts-emoji


- name: fonts | install (archlinux)
  when: "ansible_os_family == 'Archlinux'"
  kewlfft.aur.aur:
    name:
    - nerd-fonts-fira-code
    - nerd-fonts-hack
    - nerd-fonts-jetbrains-mono

- name: fonts | reload font cache (archlinux)
  when: "ansible_os_family == 'Archlinux'"
  ansible.builtin.command: fc-cache -fv
