---

- name: config | directory is present
  ansible.builtin.file:
    dest: "{{ config.path }}"
    state: directory
    mode: 0700

- include_tasks: dotfiles.yml
  tags: dotfiles

- include_tasks: git.yml
  tags: git

- include_tasks: ssh.yml
  tags: ssh

- include_tasks: wallpapers.yml
  tags: wallpapers

- include_tasks: gpg.yml
  tags: gpg

- include_tasks: tmux.yml
  tags: tmux

- include_tasks: fonts.yml
  tags: fonts

- include_tasks: neovim.yml
  tags: neovim
