---

- name: config | directory is present
  ansible.builtin.file:
    dest: "{{ config.path }}"
    state: directory
    mode: 0700

- include: dotfiles.yml
  tags: dotfiles

- include: git.yml
  tags: git

- include: ssh.yml
  tags: ssh

- include: wallpapers.yml
  tags: wallpapers

- include: gpg.yml
  tags: gpg

- include: tmux.yml
  tags: tmux

- include: fonts.yml
  tags: fonts