---

- name: config | directory is present
  ansible.builtin.file:
    dest: "$HOME/.config"
    state: directory
    mode: 0700

- name: dotfiles
  include: dotfiles.yml

- name: git
  include: git.yml

- name: ssh
  include: ssh.yml
  tags: ssh
