---

- name: neovim | install (macos)
  when: "ansible_os_family == 'Darwin'"
  community.general.homebrew:
    name:
    - luajit
    - neovim
    state: present

- name: neovim | install (archlinux)
  become: true
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    name: neovim
    state: present

- name: neovim | link config
  ansible.builtin.file:
    src: "{{ neovim.config_src }}"
    dest: "{{ neovim.config_dest }}"
    state: link

- name: neovim | lsp | install language servers (arch)
  become: true
  when: "ansible_os_family == 'Archlinux'"
  community.general.pacman:
    state: present
    name:
    - rust-analyzer
    - pyright
    - gopls
    - bash-language-server
