---
- name: wallpapers | ensure dir exists
  ansible.builtin.file:
    dest: "{{ '/'.join(wallpapers.dest.split('/')[:-1]) }}"
    state: directory
    mode: 0755

- name: wallpapers | link
  ansible.builtin.file:
    src: "{{ wallpapers.src }}"
    dest: "{{ wallpapers.dest }}"
    state: link
