---
- name: darwin | install cask
  homebrew:
    name: "{{ shell_tools.homebrew_cask_packages }}"
    state: present

- name: darwin | install non-cask
  homebrew:
    name: "{{ shell_tools.homebrew_packages }}"
    state: present
