---
- name: Install useful shell tools (Homebrew cask)
  homebrew:
    name: "{{ shell_tools.homebrew_cask_packages }}"
    state: present

- name: Install useful shell tools (non-cask)
  homebrew:
    name: "{{ shell_tools.homebrew_packages }}"
    state: present
