---
- name: OS Specific Steps
  include: "{{ ansible_os_family }}.yml"

- name: Ensure GPG directory is present
  when: "gpg_config_link == True"
  file:
    dest: "~/.gnupg"
    state: directory
    mode: 0700
    owner: "{{ ansible_user_id }}"

- name: Link GPG config (Mac)
  when: "gpg_config_link == True and ansible_distribution == 'MacOSX'"
  file:
    src: "{{ gpg_config_src_mac }}"
    dest: "{{ gpg_config_dst }}"
    state: link
    mode: 0644

- name: Link GPG config (Arch)
  when: "gpg_config_link == True and ansible_distribution != 'MacOSX'"
  file:
    src: "{{ gpg_config_src_linux }}"
    dest: "{{ gpg_config_dst }}"
    state: link
    mode: 0644

- name: Import GPG keys
  shell: curl https://keybase.io/sabnatarajan/pgp_keys.asc | gpg --import
