---
- name: Install Neovim (Nightly)
  homebrew:
    name: 
      - luajit
      - neovim
    state: head
  when: "ansible_distribution == 'MacOSX'"

- name: Link Neovim config
  file:
    src: "{{ neovim_config_src }}"
    dest: "{{ neovim_config_dst }}"
    state: link
    

