---

config:
  path: "$HOME/.config"
  shell: fish

dotfiles:
  repo: "https://github.com/sabnatarajan/dotfiles.git"
  path: "$HOME/git/dotfiles"

git:
  config_src: "{{ dotfiles.path }}/git"
  config_dest: "{{ config.path }}/git"

ssh:
  config_dir: "~/.ssh"
  config_src: "{{ dotfiles.path }}/ssh/config"
  config_dest: "$HOME/.ssh/config"

gpg:
  config_dir: "~/.gnupg"
  config_src_mac: "{{ dotfiles.path }}/gnupg/gpg-agent-mac.conf"
  config_src_linux: "{{ dotfiles.path }}/gnupg/gpg-agent-linux.conf"

fish:
  config_src: "{{ dotfiles.path }}/fish"
  config_dest: "{{ config.path}}/fish"

  fisher_install: true
  fisher_install_plugins: true
  fisher_url: https://git.io/fisher
  fisher_dest: /tmp/fisher.fish

alacritty:
  config_src: "{{ dotfiles.path }}/alacritty"
  config_dest: "{{ config.path }}/alacritty"

wallpapers:
  src: "{{ dotfiles.path }}/wallpapers"
  dest: $HOME/.local/share/wallpapers

tmux:
  config_src: "{{ dotfiles.path }}/tmux"
  config_dest: "{{ config.path }}/tmux"

neovim:
  config_src: "{{ dotfiles.path }}/nvim"
  config_dest: "{{ config.path }}/nvim"

karabiner:
  config_src: "{{ dotfiles.path }}/karabiner"
  config_dest: "{{ config.path }}/karabiner"

starship:
  config_src: "{{ dotfiles.path }}/starship"
  config_dest: "{{ config.path }}/starship"

xorg:
  config_src: "{{ dotfiles.path }}/X11"
  config_dest: "{{ config.path }}/X11"

window_mgr:
  name: herbstluftwm
  config_src: "{{ dotfiles.path }}/herbstluftwm"
  config_dst: "{{ config.path }}/herbstluftwm"

  polybar:
    enabled: true
    config_src: "{{ dotfiles.path }}/polybar"
    config_dst: "{{ config.path }}/polybar"

  picom:
    enabled: true
    config_src: "{{ dotfiles.path }}/picom"
    config_dst: "{{ config.path }}/picom"

shell_tools:
  - { name: starship }
  - { name: jq }
  - { name: exa }
  - { name: ripgrep }
  - { name: fd }
  - { name: fzf }
  - { name: kubectl }
  - { name: kubectx }
  - { name: k9s }
  - { name: lazygit }
  - { name: ncdu }
  - { name: nmap }
  - { name: ripgrep }
  - { name: telnet, skip: ['archlinux'] }
  - { name: watch, skip: ['archlinux'] }
  - { name: lazygit }
  - { name: bat }
  - { name: git-delta }
  - { name: bind-tools, skip: ['darwin'] }
  - { name: inetutils, skip: ['darwin'] }
