---

config:
  path: "$HOME/.config"

dotfiles:
  repo: "https://github.com/sabnatarajan/dotfiles.git"
  path: "$HOME/dotfiles"

git:
  config_src: "{{ dotfiles.path }}/git"
  config_dest: "{{ config.path }}/git"
