---

config:
  path: "$HOME/.config"

dotfiles:
  repo: "https://github.com/sabnatarajan/dotfiles.git"
  path: "$HOME/git/dotfiles"

git:
  config_src: "{{ dotfiles.path }}/git"
  config_dest: "{{ config.path }}/git"

ssh:
  config_dir: "~/.ssh"
  config_src: "{{ dotfiles.path }}/ssh/config"
  config_dest: "$HOME/.ssh/config"

fish:
  config_src: "{{ dotfiles.path }}/fish"
  config_dest: "{{ config.path}}/fish"

  fisher_install: true
  fisher_install_plugins: true
  fisher_url: https://git.io/fisher
  fisher_dest: /tmp/fisher.fish
