---
- name: Install Fira Code
  become: true
  become_user: "{{ ansible_user_id }}"
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf
    dest: "'~/.local/share/fonts/Fira Code Regular Font Complete.ttf'"