---
- name: Tap the Homebrew fonts
  when: "ansible_distribution == 'MacOSX'"
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install Fonts (MacOS)
  when: "ansible_distribution == 'MacOSX'"
  homebrew_cask:
    name: "{{ fonts_homebrew_packages }}"
    state: present
