---
- name: Create font directory
  when: "ansible_distribution in ['Archlinux','Ubuntu','RedHat','Fedora']"
  file:
    path: "$HOME/.local/share"
    state: directory
    mode: "0644"

- name: OS-specific install
  include: "{{ ansible_os_family }}.yml"