---
- name: Create font directory
  when: "ansible_distribution in ['Archlinux','Ubuntu','RedHat','Fedora']"
  become: true
  become_user: "{{ ansible_user_id }}"
  file:
    dest: "~/.local/share/fonts"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_id }}"

- name: OS-specific install
  include: "{{ ansible_os_family }}.yml"